---
- name: Ensure Docker is Absent
  package:
    name: '{{ item }}'
    state: absent
  with_items: '{{ docker_remove_packages }}'
  when: (docker_remove_packages is defined and docker_upgrade == true)
  register: remove_items

- name: Install Docker
  package:
    name: '{{ docker_package }}'
    state: present

- name: Check for Docker-Compose
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Remove Docker-Compose if not up to date
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes
