---
- name: Get docker status
  command: /usr/bin/docker stats --no-stream
  register: docker_stats

- name: Start registry
  command: /usr/bin/docker run -d -p 5000:5000 --name registry registry:2
  when: docker_stats.stdout.find('registry') == -1

- name: Check docker images
  command: /usr/bin/docker images {{ item }}
  with_items:
    - "{{ docker_pull }}"
  register: images

- name: Pull docker images
  command: /usr/bin/docker pull "{{ item.cmd[-1] }}"
  async: 600
  poll: 15
  with_items: "{{ images.results }}"
  when: (item.stdout_lines | length != 2)
